#*** Main Policy for nmeta - NFPS Load Test
#*** Written in YAML
#
tc_policies:
    # Traffic Classification Policies:
    'Basic TC Use Case':
        comment: Basic TC Use Case
        rule_set: tc_ruleset_1
        port_set: all_access_ports
        mode: active
#
tc_rules:
    # Traffic Classification Rulesets and Rules
    tc_ruleset_1:
        - comment: Constrained Bandwidth Traffic
          match_type: any
          conditions_list:
              - match_type: any
                tcp_src: 1234
                tcp_dst: 1234
          actions:
            set_qos: constrained_bw
            set_desc: description="Constrained Bandwidth Traffic"
        - comment: Constrained Bandwidth Traffic (Statistical)
          match_type: any
          conditions_list:
              - match_type: any
                statistical: 'statistical_qos_bandwidth_1'
          actions:
            set_qos: classifier_return
            set_desc: description="Statistical TC Control of Traffic QoS Treatment"
        - comment: DDoS Detection (Machine Learning)
          match_type: any
          conditions_list:
              - match_type: any
                statistical: "ml_ddos_random_forest"
          actions:
            set_qos: classifier_return
            set_desc: description="Detection of DDoS attack traffic."

#
identity:
    # Control how identity information is collected
    # This is a 1 for on and 0 for off but will later tie to set of
    # ports on which to run it
    #
    # Turn this on to collect ARP MAC address to IPv4 address mappings:
    arp: 1
    #
    # Turn this on to collect Link Layer Discovery Protocol information:
    lldp: 1
    #
    # Turn this on to collect DNS reply data matching services to IP addresses:
    dns: 1
    #
    # Turn this on to collect DHCP information about address allocations and
    # hostnames:
    dhcp: 1
#
qos_treatment:
    # Control Quality of Service (QoS) treatment mapping of
    #  names to output queue numbers:
    default_priority: 0
    constrained_bw: 1
    high_priority: 2
    low_priority: 3
#
port_sets:
    # Port Sets control what data plane ports policies and
    #  features are applied on:
    all_access_ports:
        - 'sw1-bordeaux':
            DPID: 1
            ports: 1-3,5,66
        - 'swn-bordeaux':
            DPID: 255
            ports: 3,5
        - 'Switch 1':
            DPID: 8796748549206
            ports: 1-5
